In [6]:
import numpy as np
from PIL import Image
import pandas as pd

In [7]:

df =  pd.read_excel ('bdd.xlsx')
df=df.drop(['Region', 'City','Area','District ID', 'District Name', 'Salesman Name', 'Customer No','BUID', 'Points','Price', 'Value', 'Discount','Item ID','Qty'], axis=1)
df['Date']=pd.to_datetime(df['Date']).dt.normalize()
df['Day'] = df['Date'].dt.day_name()
df

,Salesman No,Customer Name,Invoice ID,Date,Time,Item Name,Net,Day
0,PS16F13,bilel amrani,PS16F1312660,2023-05-02,2023-05-02 11:05:17,Bref 900ml javel disinf,1038.0,Tuesday
1,PS16F13,bilel amrani,PS16F1312660,2023-05-02,2023-05-02 11:05:17,Le Chat HS 750 gr,2700.0,Tuesday
2,PS16F13,bilel amrani,PS16F1312660,2023-05-02,2023-05-02 11:05:17,Pril ISIS Cold Power liquid 650 ML Lemon,3960.0,Tuesday
3,PS16F13,bilel amrani,PS16F1312660,2023-05-02,2023-05-02 11:05:17,"Le Chat Savon de Marseille 2,5L",1630.0,Tuesday
4,PS16F13,bilel amrani,PS16F1312660,2023-05-02,2023-05-02 11:05:17,"Le Chat Reg 2,5L Adv21 RL",1630.0,Tuesday
...,...,...,...,...,...,...,...,...
5199,SWS16F01,Rachid,SWS16F0103898,2023-05-04,2023-05-04 11:20:07,Pril ISIS Cold Power liquid 3L Lemon,13040.0,Thursday
5200,SWS16F01,Rachid,SWS16F0103898,2023-05-04,2023-05-04 11:20:07,Bref 900ml javel disinf,55080.0,Thursday
5201,SWS16F01,Rachid,SWS16F0103898,2023-05-04,2023-05-04 11:20:07,Pril ISIS Cold Power liquid 650 ML Lemon,0.0,Thursday
5202,SWS16F01,Rachid,SWS16F0103898,2023-05-04,2023-05-04 11:20:07,Bref 900ml javel disinf,0.0,Thursday
5203,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN

In [9]:
df2=df.groupby(['Item Name','Salesman No'])['Net'].sum()

In [10]:
df2

Item Name                                 Salesman No
Bref 1.75L Javel disinf                   MM16F01         72996.0
                                          PS16F01         21390.0
                                          PS16F02         36270.0
                                          PS16F03         11160.0
                                          PS16F04         24180.0
                                                           ...
Pril ISIS Cold Power liquid 650 ML Lemon  PS16F14        229680.0
                                          PS16F15        176220.0
                                          PS16F16        213840.0
                                          PS16F17        217800.0
                                          SWS16F01       937992.0
Name: Net, Length: 318, dtype: float64

In [11]:
df2.to_frame

<bound method Series.to_frame of Item Name                                 Salesman No
Bref 1.75L Javel disinf                   MM16F01         72996.0
                                          PS16F01         21390.0
                                          PS16F02         36270.0
                                          PS16F03         11160.0
                                          PS16F04         24180.0
                                                           ...
Pril ISIS Cold Power liquid 650 ML Lemon  PS16F14        229680.0
                                          PS16F15        176220.0
                                          PS16F16        213840.0
                                          PS16F17        217800.0
                                          SWS16F01       937992.0
Name: Net, Length: 318, dtype: float64>